//
//  GameInteractor.swift
//  GameShowApp
//
//  Created by Liliane Bezerra Lima on 23/05/16.
//  Copyright (c) 2016 Gabriel Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol GameInteractorInput
{
  func doSomething()
  func selectAnswer(request: GameScoreRequest)
}

protocol GameInteractorOutput
{
  func presentSomething(response: GameResponse)
  func presentScore(response: GameScoreResponse)
}

class GameInteractor: GameInteractorInput
{
    var output: GameInteractorOutput!
    var worker: GameWorker!
    var workerScore:GameScoreWorker!
    
  
  // MARK: Business logic
  
  func doSomething() {
    worker = GameWorker()
    worker.getAnswerWork { (question) in
        var response = GameResponse()
        response.question = question
        self.output.presentSomething(response)
    }
  }
    
    func selectAnswer(request: GameScoreRequest) {
        workerScore = GameScoreWorker()
        let score = workerScore.calculateScore(request.level!)
        var response = GameScoreResponse()
        response.score = score
        output.presentScore(response)
    }
}
