//
//  GameConfigurator.swift
//  GameShowApp
//
//  Created by Liliane Bezerra Lima on 23/05/16.
//  Copyright (c) 2016 Gabriel Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

// MARK: Connect View, Interactor, and Presenter

extension GameViewController: GamePresenterOutput {
  override func prepareForSegue(segue: UIStoryboardSegue, sender: AnyObject?)
  {
    router.passDataToNextScene(segue)
  }
}

extension GameInteractor: GameViewControllerOutput {
}

extension GamePresenter: GameInteractorOutput {
}

class GameConfigurator {
  // MARK: Object lifecycle
  
  class var sharedInstance: GameConfigurator
  {
    struct Static {
      static var instance: GameConfigurator?
      static var token: dispatch_once_t = 0
    }
    
    dispatch_once(&Static.token) {
      Static.instance = GameConfigurator()
    }
    
    return Static.instance!
  }
  
  // MARK: Configuration
  
  func configure(viewController: GameViewController) {
    let router = GameRouter()
    router.viewController = viewController
    
    let presenter = GamePresenter()
    presenter.output = viewController
    
    let interactor = GameInteractor()
    interactor.output = presenter
    
    viewController.output = interactor
    viewController.router = router
  }
}
