//
//  GameWorker.swift
//  GameShowApp
//
//  Created by Liliane Bezerra Lima on 23/05/16.
//  Copyright (c) 2016 Gabriel Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class GameWorker {
  // MARK: Business Logic
  
    func getAnswerWork(completionHandler: (question:Question, sucess:Bool) -> ()) {
    let dbManager = ModelManager.sharedInstance
        dbManager.getCurrentQuestion { (question, sucess) in
            completionHandler(question: question, sucess: sucess)
        }
  }
    
    func nextQuestion(completionHandler: (question:Question, sucess:Bool) -> ()) {
        let dbManager = ModelManager.sharedInstance
        dbManager.getNextQuestion { (question, sucess) in
            completionHandler(question: question, sucess: sucess)
        }
    }
}
