//
//  GameScoreWorker.swift
//  GameShowApp
//
//  Created by Liliane Bezerra Lima on 24/05/16.
//  Copyright (c) 2016 Gabriel Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

class GameScoreWorker {
  // MARK: Business Logic
  
    func calculateScore(score:Int) ->Int {
        return 100 * score
        
    
  }
}
