//
//  SinglePlayerPresenter.swift
//  GameShowApp
//
//  Created by Liliane Bezerra Lima on 23/05/16.
//  Copyright (c) 2016 Gabriel Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SinglePlayerPresenterInput
{
  func presentSomething(response: SinglePlayerResponse)
}

protocol SinglePlayerPresenterOutput: class
{
  func displaySomething(viewModel: SinglePlayerViewModel)
}

class SinglePlayerPresenter: SinglePlayerPresenterInput
{
  weak var output: SinglePlayerPresenterOutput!
  
  // MARK: Presentation logic
  
  func presentSomething(response: SinglePlayerResponse)
  {
    // NOTE: Format the response from the Interactor and pass the result back to the View Controller
    
    let viewModel = SinglePlayerViewModel()
    output.displaySomething(viewModel)
  }
}
