//
//  SinglePlayerInteractor.swift
//  GameShowApp
//
//  Created by Liliane Bezerra Lima on 23/05/16.
//  Copyright (c) 2016 Gabriel Alberto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol SinglePlayerInteractorInput
{
  func doSomething(request: SinglePlayerRequest)
}

protocol SinglePlayerInteractorOutput
{
  func presentSomething(response: SinglePlayerResponse)
}

class SinglePlayerInteractor: SinglePlayerInteractorInput
{
  var output: SinglePlayerInteractorOutput!
  var worker: SinglePlayerWorker!
  
  // MARK: Business logic
  
  func doSomething(request: SinglePlayerRequest)
  {
    // NOTE: Create some Worker to do the work
    
    worker = SinglePlayerWorker()
    worker.doSomeWork()
    
    // NOTE: Pass the result to the Presenter
    
    let response = SinglePlayerResponse()
    output.presentSomething(response)
  }
}
